CREATE TABLE EMP (EMPNO INTEGER UNIQUE PRIMARY KEY,
						ENAME VARCHAR(20) NOT NULL,
						MRG INTEGER,
						HIREDATE DATETIME NOT NULL,
						SAL INTEGER NOT NULL,
						COMM INTEGER,
						DEPTNO INTEGER);